#!/bin/bash

APP_NAME=$1
DEPLOYMENT_GROUP_NAME=$2
COMMIT_ID=$3
REPO=$4

aws deploy create-deployment --region us-west-2 --application-name "$APP_NAME" --deployment-group-name "$DEPLOYMENT_GROUP_NAME" --github-location commitId="$COMMIT_ID",repository="$REPO"